name: Node CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        command:
          - test: npm test
          - test: npm run type-check
          - test: npm run tslint
          - test: npm run standard
          - test: npm run jest
          - test: npm run prepublishOnly
          - pnpm: --frozen-lockfile
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - name: Install dependencies
        run: pnpm recursive install ${{ matrix.command.pnpm }}
      - name: Test
        env:
          CI: 'true'
        run: ${{ matrix.command.test }}
